version: '3.8'
services:
  supabase-db:
    image: supabase/postgres:15.1.0.117
    container_name: toolkit-supabase-db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: toolkit_db
      POSTGRES_USER: toolkit_user
      POSTGRES_PASSWORD: toolkit_pass_secure_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toolkit_user -d toolkit_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  supabase-studio:
    image: supabase/studio:20240101-ce42139
    container_name: toolkit-supabase-studio
    ports:
      - "3000:3000"
    environment:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_REST_URL: http://localhost:54321/rest/v1/
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      POSTGRES_PASSWORD: toolkit_pass_secure_2024
    depends_on:
      supabase-db:
        condition: service_healthy

volumes:
  db_data: